/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package DAW;

/**
 *
 * @author theasker
 */
public class FormCalculadora extends javax.swing.JFrame {

  /**
   * Creates new form FormCalculadora
   */
  public FormCalculadora() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    RespuestajLabel4 = new javax.swing.JLabel();
    Operador1TextField1 = new javax.swing.JTextField();
    Operador2TextField2 = new javax.swing.JTextField();
    SumaButton1 = new javax.swing.JButton();
    RestaButton2 = new javax.swing.JButton();
    MultiplicacionButton3 = new javax.swing.JButton();
    DivisionButton4 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Formulario Calculadora");

    jLabel1.setDisplayedMnemonic('C');
    jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Calculadora ..");

    jLabel2.setDisplayedMnemonic('C');
    jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    jLabel2.setText("Primer Operador:");

    jLabel3.setDisplayedMnemonic('C');
    jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    jLabel3.setText("Segundo Operador:");

    RespuestajLabel4.setDisplayedMnemonic('C');
    RespuestajLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

    SumaButton1.setText("Suma");
    SumaButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SumaButton1ActionPerformed(evt);
      }
    });

    RestaButton2.setText("Resta");
    RestaButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        RestaButton2ActionPerformed(evt);
      }
    });

    MultiplicacionButton3.setText("Multiplicación");
    MultiplicacionButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        MultiplicacionButton3ActionPerformed(evt);
      }
    });

    DivisionButton4.setText("División");
    DivisionButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        DivisionButton4ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addComponent(RespuestajLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(SumaButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(RestaButton2))
                  .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addGap(3, 3, 3)
                    .addComponent(Operador1TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(MultiplicacionButton3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(DivisionButton4))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Operador2TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)))))
        .addGap(0, 7, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(33, 33, 33)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(jLabel3)
          .addComponent(Operador2TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(Operador1TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(15, 15, 15)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(DivisionButton4)
          .addComponent(MultiplicacionButton3)
          .addComponent(RestaButton2)
          .addComponent(SumaButton1))
        .addGap(18, 18, 18)
        .addComponent(RespuestajLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(20, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void SumaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumaButton1ActionPerformed
    try{
      Double respuesta = ((Double.parseDouble(Operador1TextField1.getText()))+
                          Double.parseDouble(Operador2TextField2.getText()));
      RespuestajLabel4.setText("La suma es de: "+respuesta);
    }catch (NumberFormatException nfe){
      RespuestajLabel4.setText("Hay que introducir un número");
    }
  }//GEN-LAST:event_SumaButton1ActionPerformed

  private void MultiplicacionButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicacionButton3ActionPerformed
    try{
      Double respuesta = ((Double.parseDouble(Operador1TextField1.getText()))*
                          Double.parseDouble(Operador2TextField2.getText()));
      RespuestajLabel4.setText("La Multiplicación es de: "+respuesta);
    }catch (NumberFormatException nfe){
      RespuestajLabel4.setText("Hay que introducir un número");
    }
  }//GEN-LAST:event_MultiplicacionButton3ActionPerformed

  private void RestaButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaButton2ActionPerformed
    try{
      Double respuesta = ((Double.parseDouble(Operador1TextField1.getText()))-
                          Double.parseDouble(Operador2TextField2.getText()));
      RespuestajLabel4.setText("La resta es de: "+respuesta);
    }catch (NumberFormatException nfe){
      RespuestajLabel4.setText("Hay que introducir un número");
    }  
  }//GEN-LAST:event_RestaButton2ActionPerformed

  private void DivisionButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionButton4ActionPerformed
    try{
      Double respuesta = ((Double.parseDouble(Operador1TextField1.getText()))/
                          Double.parseDouble(Operador2TextField2.getText()));
      RespuestajLabel4.setText("La división es de: "+respuesta);
    }catch (NumberFormatException nfe){
      RespuestajLabel4.setText("Hay que introducir un número");
    }
  }//GEN-LAST:event_DivisionButton4ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FormCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FormCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FormCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FormCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FormCalculadora().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton DivisionButton4;
  private javax.swing.JButton MultiplicacionButton3;
  private javax.swing.JTextField Operador1TextField1;
  private javax.swing.JTextField Operador2TextField2;
  private javax.swing.JLabel RespuestajLabel4;
  private javax.swing.JButton RestaButton2;
  private javax.swing.JButton SumaButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  // End of variables declaration//GEN-END:variables
}
